spring:
  datasource:
    url: jdbc:h2:file:./target/db/glfbe
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
  mail:
    host: cs03.imgwebsolutions.it
    username: info@tilinkotool.it
    port: 25
    password: Osuu19_2

gfl:
  ftp:
    host: 80.241.142.27
    user: admintlt
    password: Qw9o&26g
  suggestUrl: https://suggestqueries.google.com/complete/search?output=toolbar&hl=it&q={keyWord}
