spring:
  datasource:
    url: jdbc:h2:file:./target/db/glfbe
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
  liquibase:
    enabled: true
    change-log: db/liquibase/db.changelog-master.xml
  mail:
    host: mail.tilinko.it
    username: customers@tilinko.it
    port: 465
    password: r[.UDPA;orXl
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: "javax.net.ssl.SSLSocketFactory"
  main:
    allow-circular-references: true
tilinko:
  confirm-base-url: "http://localhost:4200/confirm?code="
  confirm-email-base-url: "http://localhost:4200/confirm-email?code="
  reset-password-base-url: "http://localhost:4200/reset-password?code="
  customer-base-url: "http://localhost:4200"

tilinkotool:
  hintPositiveLinksRatio: "Dal report del tuo sito abbiamo rilevato che hai il %s link dofollow e il %s di link nofollow. Ti consigliamo di aumentare la quota di link dofollow che puntano al tuo sito."
  hintNegativeLinksRatio: "Dal report del tuo sito abbiamo rilevato che hai il %s link dofollow e il %s di link nofollow. Ti consigliamo di aumentare la quota di link nofollow che puntano al tuo sito."
  hintNegativeTextBrandRatio: "Dal report del tuo sito abbiamo rilevato che hai il %s di anchor text brand, per questo motivo ti consigliamo di acquisire link con anchor brand."
  hintPositiveTextBrandRatio: "Dal report del tuo sito abbiamo rilevato che hai il %s di anchor text brand, per questo motivo ti consigliamo di acquisire link con anchor brand manipolativa per spingere le pagine più importanti del tuo sito."
  hintLowLinks: "Hai un basso quantitativo di link che puntano al tuo sito (meno di 100). Il consiglio è quello di aumentare, in modo graduale, il numero di link così da rendere più solido il profilo link del tuo sito. Questo ti permette, anche, di subire meno danni in caso di attacchi di negative SEO da parte di competitor."

  hintLowRefDomains: "Il tuo sito web riceve un numero di link non molto alto. Anche se oggi la qualità e sicuramente molto più importante della quantità, avere un alto numero di domini referenti è molto importante per consolidare l'autorevolezza del tuo sito web agli occhi dei motori di ricerca. Inoltre aiuta a prevenire possibili danni dovuti ad attacchi di negative SEO che, seppur meno frequenti ed efficaci rispetto al passato, su siti web con un profilo link non molto autorevole possono ancora creare danni"
  hintHighRefDomains: "Il tuo sito web riceve un numero di link sufficiente in termini assoluti (va poi analizzato il mercato di riferimento). Anche se oggi la qualità e sicuramente molto più importante della quantità, avere un alto numero di domini referenti è molto importante per consolidare l'autorevolezza del tuo sito web agli occhi dei motori di ricerca. Inoltre aiuta a prevenire possibili danni dovuti ad attacchi di negative SEO che, seppur meno frequenti ed efficaci rispetto al passato, su siti web con un profilo link non molto autorevole possono ancora creare danni"
  hintMediumRefDomain: "Inoltre abbiamo riscontrato che il tuo sito web ha un numero inferiore di referring domain rispetto ai tuoi competitor. Questo potrebbe causarti problemi a livello di competitivtà e autorevolezza. Se vuoi migliorare il posizionamento sui motori di ricerca il consiglio è quello di acquisire link da testate locali, magazine generalisti e siti del tuo settore per colmare questo gap"
  hintOptimalRefDomain: "Abbiamo riscontrato che il tuo sito web ha un numero maggiore di referring domain rispetto ai tuoi competitor. Molto bene! Il consiglio è quello di continuare ad acquisire link per mantenere questo rapporto favorevole e consolidare il posizionamento sui motori di ricerca per le principali parole chiave del tuo settore"

  hintMissingDomains: "Abbiamo visto che il tuo sito non riceve link da %s. Sono siti nostri partner che potrebbero aiutarti ad aumentare l’autorevolezza del tuo sito web e migliorare il posizionamento sui motori di ricerca. Se vuoi possiamo occuparci di realizzare dei contenuti che valorizzino il tuo brand e pubblicarli sulle suddette testate."
  hintGoodComparisonWithCompetitor: "Dall'analisi dei competitor abbiamo rilevato che il tuo sito ha più referring domain rispetto ai tuoi diretti concorrenti. Continua così in modo da aumentare l'autorevolezza del tuo brand agli occhi dei motori di ricerca e degli utenti"
  hintBadComparisonWithCompetitor: "Dall'analisi dei competitor abbiamo rilevato che il tuo sito ha meno referring domain rispetto ai tuoi diretti concorrenti. Devi colmare il divario in modo da aumentare l'autorevolezza del tuo brand agli occhi dei motori di ricerca e degli utenti"
  hintMediumComparisonWithCompetitor : "Dall'analisi dei competitor abbiamo rilevato che il tuo sito ha meno referring domain rispetto a %s ma di più di %s. Il consiglio è quello di aumentare il numero di referring domain che linkano il tuo sito così da aumentare l'autorevolezza del tuo brand agli occhi dei motori di ricerca e degli utenti"
