spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gfl
    username: tilinko_usr
    password: uLCN!2kJ2
  jpa:
    show-sql: false

tilinko:
  confirm-base-url: "https://customers.tilinkotool.it/confirm?code="
  confirm-email-base-url: "https://customers.tilinkotool.it/confirm-email?code="
  reset-password-base-url: "https://customers.tilinkotool.it/reset-password?code="
  customer-base-url: "https://customers.tilinkotool.it"
