spring:
  datasource:
    url: jdbc:h2:file:./target/db/glfbe
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
  liquibase:
    enabled: true
    change-log: db/liquibase/db.changelog-master.xml
